@echo off
echo Starting Vulnerability Scanner...
echo.
echo Step 1: Installing dependencies...
call npm install
echo.
echo Step 2: Starting backend server and frontend application...
call npm run dev
